export interface FreightPayment {
  id: number;
  Timestamp?: string;
  "Payment Number"?: string;
  "Unique Number"?: string;
  "Firm Name"?: string;
  "Fms Name"?: string;
  Status?: string;
  "Transporter Name"?: string;
  "Vehicle Number"?: string;
  From?: string;
  To?: string;
  "Material Load Details"?: string;
  "Bilty Number"?: string;
  "Rate Type"?: string;
  Amount?: number;
  PostingAmount?: number;
  "Bilty Image"?: string;
  Planned?: string;
  Actual?: string;
  Delay?: number;
  Status_1?: string;
  Planned2?: string;
  Actual2?: string;
  Delay2?: number;
  Status2?: string;
  Planned3?: string;
  Actual3?: string;
  Delay3?: number;
  Status3?: string;
  Actual4?: string;
  Delay4?: number;
  created_at?: string;
  "Lift ID"?: string;
  "Party Name"?: string;
  "Billing Qty"?: number;
  "Bill Number"?: string;
  Remark?: string;
  Remark_1?: string;
  Remark2?: string;
  Remark3?: string;
  "Audit Image"?: string;
  "Transporter Bill Image"?: string;
  "Batch Number"?: string;
}
