import { UserCog, Building2, Users as UsersIcon } from 'lucide-react';
import { SYSTEM_NAV_ITEMS } from './categories';

export const EMPTY_MASTER_FORM = {
  type: "Vendor Name",
  vendorName: "",
  vendorNameKyc: "",
  typeOfKycForm: "",
  firmName: "PMMPL",
  gstNumber: "",
  phoneNumber: "",
  email: "",
  bankAccountNo: "",
  ifscCode: "",
  // Purchase Firms fields — purchase_firm has its own shape (dataName/gstin/pan/
  // poPrefix/phone) distinct from purchase_master's vendor-oriented fields above.
  dataName: "",
  gstin: "",
  pan: "",
  poPrefix: "",
  phone: "",
  transporterName: "",
  transporterName2: "",
  materialReturnTransporterName: "",
  rateType: "",
  typeOfRate: "",
  rawMaterialName: "",
  productName: "",
  itemName: "",
  uom: "MT",
  fmsName: "",
  department: "",
  groupHead: "",
  machineName: "",
  typeOfIndent: "",
  areaLifting: "",
  paymentTerm: "",
  generatedBy: "",
  aluminaRange: "",
  ironRange: "",
  apRange: "",
  bdRange: "",
  partyName: "",
  address: "",
  customerCategory: "",
  typeOfPi: "",
  marketingSalesPerson: "",
  nameOfRawMaterial: "",
  finishedGoodsName: "",
  crushingProductName: "",
  materialName: "",
  supervisorName: "",
  sfSupervisorName: "",
  testedBy: "",
  flowOfMaterial: "",
  shift: "",
  priority: "",
  status: "",
  testStatus: "",
  category: "",
  groupName: "",
  areaOfUse: "",
  defaultTerms: "",
  where: "",
  vendorGstin: "",
  vendorAddress: "",
  vendorEmail: "",
  companyName: "",
  companyAddress: "",
  companyGstin: "",
  companyPhone: "",
  companyPan: "",
  billingAddress: "",
  destinationAddress: "",
  transportType: "",
  doerName: "",
  givenBy: "",
  role: "",
  firm: "PMMPL",
};


// Settings sub-sidebar structure
export const NAV_SECTIONS = [
  {
    id: "profile",
    label: "Profile",
    icon: UserCog,
    items: [{ id: "my-profile", label: "My Profile" }],
  },
  {
    id: "user-management",
    label: "User Management",
    icon: UsersIcon,
    items: [{ id: "manage-users", label: "Manage Users" }],
  },
  {
    id: "systems",
    label: "Systems",
    icon: Building2,
    items: SYSTEM_NAV_ITEMS,
  },
];

