import { FileText, Package, Scale, Tags, Truck, UserCheck, Warehouse } from 'lucide-react';

export const ORDER_CATEGORIES = [
  {
    id: "party",
    title: "Customers & Parties",
    description: "Manage customer, client, and party records for Order.",
    icon: Warehouse,
    btnLabel: "Customer / Party",
    columnHeader: "Party Name",
    typeValue: "Party Name",
    filter: (r) => Boolean(r.partyName),
    getName: (r) => r.partyName,
  },
  {
    id: "transporter",
    title: "Transporters & Logistics",
    description: "Manage transporter and logistics providers for Order.",
    icon: Truck,
    btnLabel: "Transporter",
    columnHeader: "Transporter Name",
    typeValue: "Transporter Name",
    filter: (r) => Boolean(r.transporterName),
    getName: (r) => r.transporterName,
  },
  {
    id: "material_return_transporter",
    title: "Material Return Transporters",
    description: "Manage return logistics transporters for Order.",
    icon: Truck,
    btnLabel: "Return Transporter",
    columnHeader: "Material Return Transporter Name",
    typeValue: "Material Return Transporter Name",
    filter: (r) => Boolean(r.materialReturnTransporterName),
    getName: (r) => r.materialReturnTransporterName,
  },
  {
    id: "product",
    title: "Products & Materials",
    description: "Manage product catalogue and item configurations for Order.",
    icon: Package,
    btnLabel: "Product",
    columnHeader: "Product Name",
    typeValue: "Product Name",
    filter: (r) => Boolean(r.productName),
    getName: (r) => r.productName,
  },
  {
    id: "sales_person",
    title: "Marketing & Sales Persons",
    description: "Manage sales coordinators and marketing representatives for Order.",
    icon: UserCheck,
    btnLabel: "Sales Person",
    columnHeader: "Marketing Sales Person",
    typeValue: "Marketing Sales Person",
    filter: (r) => Boolean(r.marketingSalesPerson),
    getName: (r) => r.marketingSalesPerson,
  },
  {
    id: "pi_type",
    title: "PI Types (Type of PI)",
    description: "Manage Proforma Invoice payment conditions and types.",
    icon: FileText,
    btnLabel: "PI Type",
    columnHeader: "Type of PI",
    typeValue: "Type of PI",
    filter: (r) => Boolean(r.typeOfPi),
    getName: (r) => r.typeOfPi,
  },
  {
    id: "customer_category",
    title: "Customer Categories",
    description: "Manage customer classifications and priority categories.",
    icon: Tags,
    btnLabel: "Customer Category",
    columnHeader: "Customer Category",
    typeValue: "Customer Category",
    filter: (r) => Boolean(r.customerCategory),
    getName: (r) => r.customerCategory,
  },
  {
    id: "uom",
    title: "Units of Measurement (UOM)",
    description: "Manage measurement units for order items.",
    icon: Scale,
    btnLabel: "UOM",
    columnHeader: "Unit of Measurement",
    typeValue: "UOM",
    filter: (r) => Boolean(r.uom),
    getName: (r) => r.uom,
  },
];

