import { Layers, Package, ShieldCheck, Sliders, Tags, UserCheck } from 'lucide-react';

export const PRODUCTION_CATEGORIES = [
  {
    id: "raw_material",
    title: "Raw Materials",
    description: "Manage raw material master items for Production.",
    icon: Package,
    btnLabel: "Raw Material",
    columnHeader: "Name of Raw Material",
    typeValue: "Raw Material",
    filter: (r) => Boolean(r.nameOfRawMaterial),
    getName: (r) => r.nameOfRawMaterial,
  },
  {
    id: "finished_goods",
    title: "Finished Goods",
    description: "Manage finished goods product catalog for Production.",
    icon: Package,
    btnLabel: "Finished Good",
    columnHeader: "Finished Goods Name",
    typeValue: "Finished Goods",
    filter: (r) => Boolean(r.finishedGoodsName),
    getName: (r) => r.finishedGoodsName,
  },
  {
    id: "crushing_product",
    title: "Crushing Products",
    description: "Manage crushing product types and output configurations.",
    icon: Package,
    btnLabel: "Crushing Product",
    columnHeader: "Crushing Product Name",
    typeValue: "Crushing Product",
    filter: (r) => Boolean(r.crushingProductName),
    getName: (r) => r.crushingProductName,
  },
  {
    id: "material",
    title: "General Materials",
    description: "Manage general materials and composition elements for Production.",
    icon: Layers,
    btnLabel: "Material",
    columnHeader: "Material Name",
    typeValue: "Material",
    filter: (r) => Boolean(r.materialName),
    getName: (r) => r.materialName,
  },
  {
    id: "supervisor",
    title: "Supervisors",
    description: "Manage production supervisors and shift managers.",
    icon: UserCheck,
    btnLabel: "Supervisor",
    columnHeader: "Supervisor Name",
    typeValue: "Supervisor",
    filter: (r) => Boolean(r.supervisorName),
    getName: (r) => r.supervisorName,
  },
  {
    id: "sf_supervisor",
    title: "SF Supervisors",
    description: "Manage SF production supervisor staff.",
    icon: UserCheck,
    btnLabel: "SF Supervisor",
    columnHeader: "SF Supervisor Name",
    typeValue: "SF Supervisor",
    filter: (r) => Boolean(r.sfSupervisorName),
    getName: (r) => r.sfSupervisorName,
  },
  {
    id: "tested_by",
    title: "Tested By (QC Testers)",
    description: "Manage QC testing personnel and laboratory in-charge names.",
    icon: ShieldCheck,
    btnLabel: "Tester",
    columnHeader: "Tested By",
    typeValue: "Tested By",
    filter: (r) => Boolean(r.testedBy),
    getName: (r) => r.testedBy,
  },
  {
    id: "shift",
    title: "Shifts",
    description: "Manage production shift timings and schedules.",
    icon: Sliders,
    btnLabel: "Shift",
    columnHeader: "Shift",
    typeValue: "Shift",
    filter: (r) => Boolean(r.shift),
    getName: (r) => r.shift,
  },
  {
    id: "priority",
    title: "Priorities",
    description: "Manage production order priority levels.",
    icon: Tags,
    btnLabel: "Priority",
    columnHeader: "Priority",
    typeValue: "Priority",
    filter: (r) => Boolean(r.priority),
    getName: (r) => r.priority,
  },
  {
    id: "flow_of_material",
    title: "Flow of Material",
    description: "Manage material flow classifications and status indicators.",
    icon: Sliders,
    btnLabel: "Flow of Material",
    columnHeader: "Flow of Material",
    typeValue: "Flow of Material",
    filter: (r) => Boolean(r.flowOfMaterial),
    getName: (r) => r.flowOfMaterial,
  },
  {
    id: "status",
    title: "Statuses",
    description: "Manage operational status values for production tasks.",
    icon: Sliders,
    btnLabel: "Status",
    columnHeader: "Status",
    typeValue: "Status",
    filter: (r) => Boolean(r.status),
    getName: (r) => r.status,
  },
  {
    id: "test_status",
    title: "Test Statuses",
    description: "Manage laboratory QC test result statuses.",
    icon: ShieldCheck,
    btnLabel: "Test Status",
    columnHeader: "Test Status",
    typeValue: "Test Status",
    filter: (r) => Boolean(r.testStatus),
    getName: (r) => r.testStatus,
  },
];

