import { Building2, CreditCard, Layers, MapPin, Package, Scale, Sliders, Tags, Warehouse } from 'lucide-react';

export const STORE_CATEGORIES = [
  {
    id: "item",
    title: "Items & Products",
    description: "Manage store catalog items, inventory descriptions, and units.",
    icon: Package,
    btnLabel: "Item",
    columnHeader: "Item Name",
    typeValue: "Item",
    filter: (r) => Boolean(r.itemName),
    getName: (r) => r.itemName,
  },
  {
    id: "category",
    title: "Item Categories",
    description: "Manage classification categories for store items.",
    icon: Layers,
    btnLabel: "Category",
    columnHeader: "Category",
    typeValue: "Category",
    filter: (r) => Boolean(r.category),
    getName: (r) => r.category,
  },
  {
    id: "group_name",
    title: "Item Groups",
    description: "Manage group groupings for store inventory.",
    icon: Tags,
    btnLabel: "Group",
    columnHeader: "Group Name",
    typeValue: "Group",
    filter: (r) => Boolean(r.groupName),
    getName: (r) => r.groupName,
  },
  {
    id: "uom",
    title: "Units of Measurement (UOM)",
    description: "Manage units of measurement for store items.",
    icon: Scale,
    btnLabel: "UOM",
    columnHeader: "Unit of Measurement",
    typeValue: "UOM",
    filter: (r) => Boolean(r.uom),
    getName: (r) => r.uom,
  },
  {
    id: "vendor",
    title: "Vendors & Suppliers",
    description: "Manage vendors, suppliers, and contractor contacts.",
    icon: Warehouse,
    btnLabel: "Vendor",
    columnHeader: "Vendor Name",
    typeValue: "Vendor",
    filter: (r) => Boolean(r.vendorName),
    getName: (r) => r.vendorName,
  },
  {
    id: "company",
    title: "Companies",
    description: "Manage registered company and enterprise profiles.",
    icon: Building2,
    btnLabel: "Company",
    columnHeader: "Company Name",
    typeValue: "Company",
    filter: (r) => Boolean(r.companyName),
    getName: (r) => r.companyName,
  },
  {
    id: "department",
    title: "Departments",
    description: "Manage internal requisitioning departments.",
    icon: Building2,
    btnLabel: "Department",
    columnHeader: "Department",
    typeValue: "Department",
    filter: (r) => Boolean(r.department),
    getName: (r) => r.department,
  },
  {
    id: "area_of_use",
    title: "Areas of Use",
    description: "Manage designated application areas and usage locations.",
    icon: MapPin,
    btnLabel: "Area of Use",
    columnHeader: "Area of Use",
    typeValue: "Area of Use",
    filter: (r) => Boolean(r.areaOfUse),
    getName: (r) => r.areaOfUse,
  },
  {
    id: "where",
    title: "Locations & Where",
    description: "Manage storage locations and bin placements.",
    icon: MapPin,
    btnLabel: "Location",
    columnHeader: "Where / Location",
    typeValue: "Location",
    filter: (r) => Boolean(r.where),
    getName: (r) => r.where,
  },
  {
    id: "fms_name",
    title: "FMS Master",
    description: "Manage follow-up management system dropdown targets.",
    icon: Sliders,
    btnLabel: "FMS Name",
    columnHeader: "FMS Name",
    typeValue: "FMS Name",
    filter: (r) => Boolean(r.fmsName),
    getName: (r) => r.fmsName,
  },
  {
    id: "payment_term",
    title: "Payment Terms",
    description: "Manage commercial credit terms and conditions.",
    icon: CreditCard,
    btnLabel: "Payment Term",
    columnHeader: "Payment Term",
    typeValue: "Payment Term",
    filter: (r) => Boolean(r.paymentTerm),
    getName: (r) => r.paymentTerm,
  },
  {
    id: "address",
    title: "Addresses",
    description: "Manage billing and destination delivery addresses.",
    icon: MapPin,
    btnLabel: "Address",
    columnHeader: "Billing / Destination Address",
    typeValue: "Address",
    filter: (r) => Boolean(r.billingAddress || r.destinationAddress),
    getName: (r) => r.billingAddress || r.destinationAddress,
  },
];

