"use client";
import { useState, useEffect, useCallback } from "react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import {
  Check,
  CheckCircle,
  ChevronsUpDown,
  FileText,
  Loader2,
  XCircle,
} from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { canViewFirm } from "../utils/firmFilter";
import { API_URL, getToken } from "@/lib/auth";
import { inventoryApi } from "@/systems/inventory/lib/api";

export default function IndentForm() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isFetchingStock, setIsFetchingStock] = useState(false);
  const [isFetchingDO, setIsFetchingDO] = useState(false);
  const [formData, setFormData] = useState({
    generatedBy: "",
    vendorName: "",
    firmName: "",
    rawMaterialName: "",
    quantity: "",
    currentStock: "",
    notes: "",
    deliveryOrderNo: "",
    priority: "",
    typeOfIndent: "",
    uom: "",
    expectedRequirementDate: "",
  });
  const [errors, setErrors] = useState({});
  const [dropdownOptions, setDropdownOptions] = useState({
    generatedBy: [],
    vendorName: [],
    firmName: [],
    rawMaterialName: [],
    indentType: [],
    firmNameMapping: {},
    uom: [],
  });
  const [isLoading, setIsLoading] = useState(true);
  const [rawMaterialOpen, setRawMaterialOpen] = useState(false);
  const [rawMaterialSearch, setRawMaterialSearch] = useState("");
  const { user, allowedSteps } = useAuth();

  const normalizedIndentType = formData.typeOfIndent.trim().toLowerCase();
  const shouldShowDeliveryOrder =
    normalizedIndentType === "finished goods" ||
    normalizedIndentType.includes("traiding") ||
    normalizedIndentType.includes("trading");
  const filteredRawMaterials = dropdownOptions.rawMaterialName.filter((option) =>
    option.toLowerCase().includes(rawMaterialSearch.trim().toLowerCase()),
  );

  const APPS_SCRIPT_URL =
    "https://script.google.com/macros/s/AKfycbylQZLstOi0LyDisD6Z6KKC97pU5YJY2dDYVw2gtnW1fxZq9kz7wHBei4aZ8Ed-XKhKEA/exec";
  const SHEET_ID = "13_sHCFkVxAzPbel-k9BuUBFY-E11vdKJAOgvzhBMLMY";
  const SHEET_NAME = "INDENT-PO";

  const fetchData = useCallback(async () => {
    setIsLoading(true);
    try {
      // All dropdown/reference data now comes from the backend (purchase_master).
      const optionsRes = await fetch(`${API_URL}/purchase/master/indent-options`);
      if (!optionsRes.ok) throw new Error("Failed to fetch master data");
      const { data: masterData } = await optionsRes.json();

      // Filter firm options based on user's access (admins see every firm)
      let firmOptions = masterData.firmNameOptions || [];
      const isAdminUser = allowedSteps?.includes("admin");
      if (!isAdminUser && user?.firmName && user.firmName !== "all") {
        firmOptions = firmOptions.filter(option => canViewFirm(user.firmName, option));
      }

      let options = {
        generatedBy: masterData.generatedByOptions,
        vendorName: masterData.vendorOptions,
        firmName: firmOptions,
        rawMaterialName: masterData.materialOptions,
        indentType: masterData.indentTypeOptions,
        firmNameMapping: masterData.firmNameMapping || {},
        uom: masterData.uomOptions || [],
      };

      setDropdownOptions(options);

      // Auto-set firm if user has exactly one firm assigned and form is empty
      if (!formData.firmName && firmOptions.length === 1) {
        setFormData(prev => ({ ...prev, firmName: firmOptions[0] }));
      }
    } catch (error) {
      console.error("Error fetching master data:", error);
      toast.error("Failed to load initial form data.", {
        description: "Please try refreshing. Error: " + error.message,
        icon: <XCircle className="w-4 h-4" />,
      });
    } finally {
      setIsLoading(false);
    }
  }, [user, allowedSteps]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Auto-populate Generated By when Firm Name changes
  useEffect(() => {
    const mapping = dropdownOptions.firmNameMapping[formData.firmName];
    if (mapping && formData.generatedBy !== mapping) {
      setFormData((prev) => ({ ...prev, generatedBy: mapping }));
      setErrors((prev) => ({ ...prev, generatedBy: null }));
    }
  }, [formData.firmName, dropdownOptions.firmNameMapping, formData.generatedBy]);

  // Live-fetch Current Factory Stock from Inventory module whenever item or firm changes
  useEffect(() => {
    let isMounted = true;
    const fetchLiveStock = async () => {
      if (!formData.rawMaterialName) {
        setFormData((prev) => ({ ...prev, currentStock: "" }));
        return;
      }
      setIsFetchingStock(true);
      try {
        const params = {};
        if (formData.firmName && formData.firmName !== "all" && formData.firmName !== "All") {
          params.firm = formData.firmName;
        }
        params.search = formData.rawMaterialName.trim();
        const res = await inventoryApi.get("raw-material", params);
        if (!isMounted) return;
        const items = res?.data || [];
        const normalizedSelected = formData.rawMaterialName.trim().toLowerCase();
        const match = items.find(
          (item) => item.item_name && item.item_name.trim().toLowerCase() === normalizedSelected
        ) || items[0];

        if (match && match.actual_level !== undefined && match.actual_level !== null) {
          setFormData((prev) => ({ ...prev, currentStock: String(match.actual_level) }));
          setErrors((prev) => ({ ...prev, currentStock: null }));
        } else {
          setFormData((prev) => ({ ...prev, currentStock: "0" }));
        }
      } catch (err) {
        console.error("Failed to fetch live stock from Inventory module:", err);
      } finally {
        if (isMounted) setIsFetchingStock(false);
      }
    };

    fetchLiveStock();
    return () => {
      isMounted = false;
    };
  }, [formData.rawMaterialName, formData.firmName]);

  // Auto-fetch Delivery Order No. from Sales Order if one exists for this context
  useEffect(() => {
    let isMounted = true;
    const fetchSalesOrderDO = async () => {
      if (!shouldShowDeliveryOrder || !formData.rawMaterialName) return;
      setIsFetchingDO(true);
      try {
        const res = await fetch(`${API_URL}/order/receipt`, {
          headers: { Authorization: `Bearer ${getToken()}` },
        });
        if (!res.ok || !isMounted) return;
        const json = await res.json();
        const receipts = json.data || [];
        const normMat = formData.rawMaterialName.trim().toLowerCase();
        const normFirm = formData.firmName ? formData.firmName.trim().toLowerCase() : "";

        // Match active sales order by firm and product/material
        const matchingOrder = receipts.find((r) => {
          if (r.orderCancelledAt) return false;
          const matMatch = r.productName && r.productName.trim().toLowerCase() === normMat;
          const firmMatch = !normFirm || (r.firmName && r.firmName.trim().toLowerCase() === normFirm);
          return matMatch && firmMatch && r.doNumber;
        });

        if (matchingOrder && matchingOrder.doNumber) {
          setFormData((prev) => ({ ...prev, deliveryOrderNo: matchingOrder.doNumber }));
          setErrors((prev) => ({ ...prev, deliveryOrderNo: null }));
        }
      } catch (err) {
        console.error("Failed to check sales orders for DO Number:", err);
      } finally {
        if (isMounted) setIsFetchingDO(false);
      }
    };

    fetchSalesOrderDO();
    return () => {
      isMounted = false;
    };
  }, [shouldShowDeliveryOrder, formData.rawMaterialName, formData.firmName]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    if (errors[name]) {
      setErrors((prevErrors) => ({
        ...prevErrors,
        [name]: null,
      }));
    }
  };

  const handleSelectChange = (name, value) => {
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    if (errors[name]) {
      setErrors((prevErrors) => ({
        ...prevErrors,
        [name]: null,
      }));
    }
  };

  const validateForm = () => {
    const newErrors = {};
    if (!formData.generatedBy)
      newErrors.generatedBy = "Generated By is required.";
    if (!formData.firmName) newErrors.firmName = "Firm Name is required.";
    if (!formData.rawMaterialName)
      newErrors.rawMaterialName = "Raw Material Name is required.";
    if (!formData.expectedRequirementDate)
      newErrors.expectedRequirementDate = "Expected Requirement Date is required.";

    // Stricter check for Quantity
    if (!formData.quantity) {
      newErrors.quantity = "Quantity is required.";
    } else if (!/^-?\d*\.?\d+$/.test(formData.quantity)) {
      newErrors.quantity =
        "Please enter only valid numeric value for Quantity.";
    } else if (Number(formData.quantity) <= 0) {
      newErrors.quantity = "Quantity must be a positive number.";
    }

    // Stricter check for Current Stock
    if (formData.currentStock === "" || formData.currentStock === null || formData.currentStock === undefined) {
      newErrors.currentStock = "Current stock is required.";
    } else if (!/^-?\d*\.?\d+$/.test(String(formData.currentStock))) {
      newErrors.currentStock =
        "Please enter only valid numeric value for Current Stock.";
    }

    if (!formData.priority) newErrors.priority = "Priority is required.";
    if (!formData.typeOfIndent)
      newErrors.typeOfIndent = "Type Of Indent is required.";
    if (!formData.uom) newErrors.uom = "UOM is required.";

    if (shouldShowDeliveryOrder && !formData.deliveryOrderNo) {
      newErrors.deliveryOrderNo =
        "Delivery Order No. is required for the selected indent type.";
    }

    setErrors(newErrors); // Update state for UI error messages
    return newErrors; // Return errors immediately for synchronous check
  };

  async function handleSubmit(e) {
    e.preventDefault();
    const validationErrors = validateForm();

    if (Object.keys(validationErrors).length > 0) {
      const firstErrorKey = Object.keys(validationErrors)[0];
      toast.error("Validation Error", {
        description: validationErrors[firstErrorKey],
        icon: <XCircle className="w-4 h-4" />,
      });
      return;
    }

    setIsSubmitting(true);
    try {
      // The backend computes the next RI-XXX number atomically and inserts the indent.
      const res = await fetch(`${API_URL}/purchase/indent`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${getToken()}`,
        },
        body: JSON.stringify({
          generatedBy: formData.generatedBy,
          firmName: formData.firmName,
          rawMaterialName: formData.rawMaterialName,
          quantity: formData.quantity,
          currentStock: formData.currentStock,
          priority: formData.priority,
          typeOfIndent: formData.typeOfIndent,
          deliveryOrderNo: formData.deliveryOrderNo || null,
          notes: formData.notes,
          uom: formData.uom,
          expectedRequirementDate: formData.expectedRequirementDate,
        }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.message || "Failed to submit RI Number.");
      const riNumber = json.data.indentId;

      toast.success("Success!", {
        description: `RI Number ${riNumber} generated successfully!`,
        icon: <CheckCircle className="w-4 h-4" />,
      });

      // Reset the form
      setFormData({
        generatedBy: "",
        vendorName: "",
        firmName:
          user?.firmName && !Array.isArray(user.firmName) && String(user.firmName).toLowerCase() !== "all"
            ? user.firmName
            : "",
        rawMaterialName: "",
        quantity: "",
        currentStock: "",
        notes: "",
        deliveryOrderNo: "",
        priority: "",
        typeOfIndent: "",
        uom: "",
        expectedRequirementDate: "",
      });
      setErrors({});
    } catch (error) {
      console.error("Error submitting form:", error);
      toast.error("Submission Failed", {
        description:
          error.message || "Failed to submit RI Number. Please try again.",
        icon: <XCircle className="w-4 h-4" />,
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <Card className="w-full max-w-lg">
          <CardContent className="flex flex-col items-center justify-center p-12">
            <Loader2 className="w-12 h-12 text-primary animate-spin" />
            <p className="mt-4 ml-3 text-gray-700">Loading form data...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="w-full p-4 sm:p-6 lg:p-6">
      <Card className="w-full rounded-lg">
        <CardHeader className="p-6">
          <CardTitle className="flex items-center gap-2 text-gray-700">
            <FileText className="w-6 h-6 text-primary" />
            Indent
          </CardTitle>
          
          {user?.firmName && (
            <p className="mt-1 text-sm text-primary">
              Authorized firms:{" "}
              <span className="font-semibold">
                {user.firmName === "all" ? "All" : Array.isArray(user.firmName) ? user.firmName.join(", ") : user.firmName}
              </span>
            </p>
          )}
        </CardHeader>
        <CardContent className="p-6 sm:p-8">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div>
                <Label htmlFor="firmName">
                  Firm Name <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="firmName"
                  value={formData.firmName}
                  onValueChange={(value) =>
                    handleSelectChange("firmName", value)
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.firmName ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select firm name" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.firmName.map((option, index) => (
                      <SelectItem key={`firm-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.firmName && (
                  <p className="mt-1 text-xs text-red-500">{errors.firmName}</p>
                )}
              </div>
              <div>
                <Label htmlFor="generatedBy">
                  Generated By <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="generatedBy"
                  value={formData.generatedBy}
                  onValueChange={(value) =>
                    handleSelectChange("generatedBy", value)
                  }
                  disabled={
                    formData.firmName &&
                    dropdownOptions.firmNameMapping[formData.firmName]
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.generatedBy ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select generator" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.generatedBy.map((option, index) => (
                      <SelectItem key={`gen-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.generatedBy && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.generatedBy}
                  </p>
                )}
              </div>
              {/* <div>
                <Label htmlFor="vendorName">Vendor Name <span className="text-red-500">*</span></Label>
                <Select
                  name="vendorName"
                  value={formData.vendorName}
                  onValueChange={(value) => handleSelectChange("vendorName", value)}
                >
                  <SelectTrigger className={`mt-1 ${errors.vendorName ? "border-red-500" : ""}`}>
                    <SelectValue placeholder="Select vendor" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.vendorName.map((option, index) => (
                      <SelectItem key={`ven-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.vendorName && <p className="mt-1 text-xs text-red-500">{errors.vendorName}</p>}
              </div> */}

              <div>
                <Label htmlFor="rawMaterialName">
                  Raw Material Name <span className="text-red-500">*</span>
                </Label>
                <Popover open={rawMaterialOpen} onOpenChange={setRawMaterialOpen}>
                  <PopoverTrigger asChild>
                    <Button
                      type="button"
                      variant="outline"
                      role="combobox"
                      aria-expanded={rawMaterialOpen}
                      className={`mt-1 w-full justify-between font-normal ${
                        errors.rawMaterialName ? "border-red-500" : ""
                      }`}
                    >
                      <span className="truncate">
                        {formData.rawMaterialName || "Select material"}
                      </span>
                      <ChevronsUpDown className="w-4 h-4 ml-2 opacity-50 shrink-0" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-2">
                    <Input
                      value={rawMaterialSearch}
                      onChange={(e) => setRawMaterialSearch(e.target.value)}
                      placeholder="Search raw material..."
                      className="mb-2"
                    />
                    <div className="max-h-60 overflow-y-auto">
                      {filteredRawMaterials.length > 0 ? (
                        filteredRawMaterials.map((option, index) => (
                          <button
                            key={`mat-${index}`}
                            type="button"
                            onClick={() => {
                              handleSelectChange("rawMaterialName", option);
                              setRawMaterialOpen(false);
                              setRawMaterialSearch("");
                            }}
                            className="flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm hover:bg-slate-100"
                          >
                            <span>{option}</span>
                            {formData.rawMaterialName === option && (
                              <Check className="w-4 h-4 text-primary" />
                            )}
                          </button>
                        ))
                      ) : (
                        <p className="px-3 py-2 text-sm text-gray-500">
                          No raw material found.
                        </p>
                      )}
                    </div>
                  </PopoverContent>
                </Popover>
                {errors.rawMaterialName && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.rawMaterialName}
                  </p>
                )}
              </div>

              <div>
                <Label htmlFor="quantity">
                  Quantity <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="quantity"
                  type="text"
                  inputMode="decimal"
                  name="quantity"
                  placeholder="Enter quantity"
                  value={formData.quantity}
                  onChange={handleChange}
                  className={`mt-1 ${errors.quantity ? "border-red-500" : ""}`}
                />
                {errors.quantity && (
                  <p className="mt-1 text-xs text-red-500">{errors.quantity}</p>
                )}
              </div>

              <div>
                <Label htmlFor="uom">
                  UOM <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="uom"
                  value={formData.uom}
                  onValueChange={(value) => handleSelectChange("uom", value)}
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.uom ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select UOM" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.uom.map((option, index) => (
                      <SelectItem key={`uom-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.uom && (
                  <p className="mt-1 text-xs text-red-500">{errors.uom}</p>
                )}
              </div>

              <div>
                <Label htmlFor="currentStock" className="flex items-center justify-between">
                  <span>Current Stock <span className="text-xs text-gray-500 font-normal">(Live from Inventory)</span></span>
                  {isFetchingStock && <Loader2 className="w-3.5 h-3.5 text-primary animate-spin" />}
                </Label>
                <Input
                  id="currentStock"
                  type="text"
                  name="currentStock"
                  readOnly
                  placeholder={isFetchingStock ? "Fetching live stock..." : "0"}
                  value={formData.currentStock}
                  className={`mt-1 bg-slate-100 dark:bg-zinc-800 text-slate-700 dark:text-zinc-200 cursor-not-allowed font-medium ${errors.currentStock ? "border-red-500" : ""}`}
                />
                {errors.currentStock && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.currentStock}
                  </p>
                )}
              </div>

              <div>
                <Label htmlFor="priority">
                  Priority <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="priority"
                  value={formData.priority}
                  onValueChange={(value) =>
                    handleSelectChange("priority", value)
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.priority ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select priority" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Urgent">Urgent</SelectItem>
                    <SelectItem value="Planned">Planned</SelectItem>
                  </SelectContent>
                </Select>
                {errors.priority && (
                  <p className="mt-1 text-xs text-red-500">{errors.priority}</p>
                )}
              </div>

              <div>
                <Label htmlFor="typeOfIndent">
                  Type Of Indent <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="typeOfIndent"
                  value={formData.typeOfIndent}
                  onValueChange={(value) =>
                    handleSelectChange("typeOfIndent", value)
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.typeOfIndent ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.indentType.map((option, index) => (
                      <SelectItem key={`type-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.typeOfIndent && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.typeOfIndent}
                  </p>
                )}
              </div>

              <div>
                <Label htmlFor="expectedRequirementDate">
                  Expected Requirement Date <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="expectedRequirementDate"
                  type="date"
                  name="expectedRequirementDate"
                  value={formData.expectedRequirementDate}
                  onChange={handleChange}
                  className={`mt-1 ${errors.expectedRequirementDate ? "border-red-500" : ""}`}
                />
                {errors.expectedRequirementDate && (
                  <p className="mt-1 text-xs text-red-500">{errors.expectedRequirementDate}</p>
                )}
              </div>

              {shouldShowDeliveryOrder && (
                <div className="lg:col-span-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="deliveryOrderNo">
                      Delivery Order No. <span className="text-red-500">*</span>
                    </Label>
                    {isFetchingDO && (
                      <span className="flex items-center text-xs text-gray-500 gap-1">
                        <Loader2 className="w-3 h-3 animate-spin" /> Checking Sales Orders...
                      </span>
                    )}
                  </div>
                  <Input
                    id="deliveryOrderNo"
                    type="text"
                    name="deliveryOrderNo"
                    placeholder="Enter or auto-populated DO number"
                    value={formData.deliveryOrderNo}
                    onChange={handleChange}
                    className={`mt-1 ${errors.deliveryOrderNo ? "border-red-500" : ""}`}
                  />
                  {errors.deliveryOrderNo && (
                    <p className="mt-1 text-xs text-red-500">{errors.deliveryOrderNo}</p>
                  )}
                </div>
              )}
            </div>

            <div className="lg:col-span-3">
              <Label htmlFor="notes">Notes</Label>
              <Textarea
                id="notes"
                name="notes"
                placeholder="Enter any additional notes or requirements"
                value={formData.notes}
                onChange={handleChange}
                className="min-h-[80px] mt-1"
              />
            </div>

            <div className="pt-4">
              <Button
                type="submit"
                className="w-full font-semibold rounded-md"
                disabled={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Submitting...
                  </>
                ) : (
                  "Generate Entry"
                )}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
